version: '3'

services:
    archivebox:
        build: .
        stdin_open: true
        tty: true
        environment:
            - USE_COLOR=False
            - SHOW_PROGRESS=False
        volumes:
            - ./data:/data
        command: bash -c 'echo "https://github.com/pirate/ArchiveBox" | /bin/archive; tail -f /dev/null'

    nginx:
        image: 'nginx'
        ports:
            - '8098:80'
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./data:/var/www
